services:
  db:
    image: postgres:16.3-alpine3.20
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
    networks:
      - tincan-network

  backend:
    image: ${DOCKER_HUB_USERNAME}/tincan-backend:latest
    command: /rails/bin/docker-entrypoint ./bin/rails server
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_HOST=db
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - ./log:/rails/log
    networks:
      - tincan-network
    depends_on:
      - db

  frontend:
    image: ${DOCKER_HUB_USERNAME}/tincan-frontend:latest
    networks:
      - tincan-network

  nginx:
    image: ${DOCKER_HUB_USERNAME}/tincan-nginx:latest
    ports:
      - "80:8080" # Map 8080 (container) to 80 (host)
    depends_on:
      - frontend
      - backend
    volumes:
      - ./log:/var/log/nginx
    networks:
      - tincan-network

networks:
  tincan-network:
    driver: bridge

volumes:
  pgdata:
